version: '3.8'

services:
  # Backend service
  antara-backend:
    build:
      context: ./antara_engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=sqlite:///./data/antara.db
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
      - DEBUG=true
      - LOG_LEVEL=INFO
    volumes:
      - ./antara_engine/data:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Frontend service (for development)
  antara-frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    depends_on:
      - antara-backend
    restart: unless-stopped

networks:
  default:
    name: antara-network
