services:
  - type: web
    name: antara-engine
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./antara.db
      - key: ALLOWED_ORIGINS
        value: https://antara-frontend.vercel.app,http://localhost:3000,http://localhost:5173
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
